### ISSUE TITLE
Grids! @thatkidmadrid

### ISSUE THREAD

**Issue by adrianna16** [adrianna16/components-on-a-grid#1]
Hello, I swear I have tried every possible grid template, grid columns, grid rows and I still cannot seem to figure it out. I am aware that my current grid stuff probably isn't even close to correct this was just my last try before I asked for help. it is starting to get very frustrating

**Comment by thatkidmadrid** [comment]
ok so I think you’ve caught some weird stuff in your first commit to css and are in a better direction for sure
so don’t feel discouraged

something that may help is remembering what the the display: contents in the header  is doing

I’m not sure if I was very clear in class, but essentially what it’s doing is allowing the contents of the header to be placed on the grid

if it did not have this property, only the header would align with the grid

so, you can ignore trying to use the grid properties to position the header, and focus on using them on the contents of the header
