### ISSUE TITLE
Solution!

### ISSUE THREAD

**Issue by adrianna16** [adrianna16/components-on-a-grid#3]
sorry for the lack of enthusiasm in this recording @thatkidmadrid
[hanselman-adrianna-compnents-on-a-grid.m4a.zip](https://github.com/adrianna16/components-on-a-grid/files/7220980/hanselman-adrianna-compnents-on-a-grid.m4a.zip)

**Comment by thatkidmadrid** [comment]
lol no problem

I noticed you skipped the asterisks
you can say something like
"target star, star before, and star after" or replace the word star with "asterisk" or "wildcard" and developers will understand what you mean
